baseURL = "http://merfeld.info/"
title = "Reinhard Merfeld"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "reinhardmerfeld"

[params]

    author = "Reinhard Merfeld"
    info = "Full Stack Developer"
    description = "Reinhard Merfeld's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    quote = "It always seems unpossible until it's done"
    quote_author = "Nelson Mandela"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-sm"
    weight = 1
    url = "https://github.com/rmerfeld/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-sm"
    weight = 2
    url = "https://www.instagram.com/merfeldo/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-sm"
    weight = 3
    url = "https://twitter.com/merfeldo/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-sm"
    weight = 4
    url = "mailto:reinhard@merfeld.info/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"