[build]
  publish = "public"
  command = "hugo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.49.2/extended"

[context.deploy-preview]
  command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49.2/extended"
